import expoConfig from "eslint-config-expo/flat.js";

export default [
  {
    ignores: [
      "**/node_modules/**",
      ".expo/**",
      // Generated by Expo / tooling
      "expo-env.d.ts",
    ],
  },
  ...expoConfig,
];
