/** Common Bible book misspellings and phonetic variants (lowercase) → canonical display name. */
export const BIBLE_BOOK_MISSPELLINGS: Record<string, string> = {
  genisis: "Genesis",
  geneses: "Genesis",
  exodis: "Exodus",
  pslams: "Psalms",
  psams: "Psalms",
  mathew: "Matthew",
  zacchriah: "Zechariah",
  zachariah: "Zechariah",
  zekariah: "Zechariah",
  zecheria: "Zechariah",
  zecharia: "Zechariah",
  revelations: "Revelation",
  phillipians: "Philippians",
  galations: "Galatians",
  ephisians: "Ephesians",
  isiah: "Isaiah",
  jerimiah: "Jeremiah",
  ezikiel: "Ezekiel",
  johnn: "John",
  // Phonetic / alternate spellings
  rooht: "Ruth",
  rute: "Ruth",
  izayah: "Isaiah",
  izaiah: "Isaiah",
  isaia: "Isaiah",
  jeremiyah: "Jeremiah",
  jeremia: "Jeremiah",
  ezekial: "Ezekiel",
  danial: "Daniel",
  habbakuk: "Habakkuk",
  habacuc: "Habakkuk",
  sophonia: "Zephaniah",
  zephania: "Zephaniah",
  malachai: "Malachi",
  levitikus: "Leviticus",
  deuteronomi: "Deuteronomy",
  ecclesiastes: "Ecclesiastes",
  ecclesiasties: "Ecclesiastes",
  songofsolomon: "Song of Solomon",
  firstsamuel: "1 Samuel",
  secondsamuel: "2 Samuel",
  firstkings: "1 Kings",
  secondkings: "2 Kings",
  firstchronicles: "1 Chronicles",
  secondchronicles: "2 Chronicles",
  firstcorinthians: "1 Corinthians",
  secondcorinthians: "2 Corinthians",
  firstthessalonians: "1 Thessalonians",
  secondthessalonians: "2 Thessalonians",
  firsttimothy: "1 Timothy",
  secondtimothy: "2 Timothy",
  firstpeter: "1 Peter",
  secondpeter: "2 Peter",
  firstjohn: "1 John",
  secondjohn: "2 John",
  thirdjohn: "3 John",
};

/** Returns canonical book display name when `firstWord` is a known alias, else null. */
export function getPassageMisspellingSuggestion(firstWord: string): string | null {
  if (!firstWord || typeof firstWord !== "string") return null;
  const key = firstWord.trim().toLowerCase();
  return BIBLE_BOOK_MISSPELLINGS[key] ?? null;
}
