/** Genre label per canonical book slug (KJV order); used in testament list rows. */
export const BOOK_GENRE_BY_SLUG: Record<string, string> = {
  genesis: "Law",
  exodus: "Law",
  leviticus: "Law",
  numbers: "Law",
  deuteronomy: "Law",
  joshua: "History",
  judges: "History",
  ruth: "History",
  "1-samuel": "History",
  "2-samuel": "History",
  "1-kings": "History",
  "2-kings": "History",
  "1-chronicles": "History",
  "2-chronicles": "History",
  ezra: "History",
  nehemiah: "History",
  esther: "History",
  job: "Poetry",
  psalms: "Poetry",
  proverbs: "Poetry",
  ecclesiastes: "Poetry",
  "song-of-solomon": "Poetry",
  isaiah: "Major Prophets",
  jeremiah: "Major Prophets",
  lamentations: "Major Prophets",
  ezekiel: "Major Prophets",
  daniel: "Major Prophets",
  hosea: "Minor Prophets",
  joel: "Minor Prophets",
  amos: "Minor Prophets",
  obadiah: "Minor Prophets",
  jonah: "Minor Prophets",
  micah: "Minor Prophets",
  nahum: "Minor Prophets",
  habakkuk: "Minor Prophets",
  zephaniah: "Minor Prophets",
  haggai: "Minor Prophets",
  zechariah: "Minor Prophets",
  malachi: "Minor Prophets",
  matthew: "Gospels",
  mark: "Gospels",
  luke: "Gospels",
  john: "Gospels",
  acts: "History",
  romans: "Epistles",
  "1-corinthians": "Epistles",
  "2-corinthians": "Epistles",
  galatians: "Epistles",
  ephesians: "Epistles",
  philippians: "Epistles",
  colossians: "Epistles",
  "1-thessalonians": "Epistles",
  "2-thessalonians": "Epistles",
  "1-timothy": "Epistles",
  "2-timothy": "Epistles",
  titus: "Epistles",
  philemon: "Epistles",
  hebrews: "Epistles",
  james: "General Epistles",
  "1-peter": "General Epistles",
  "2-peter": "General Epistles",
  "1-john": "General Epistles",
  "2-john": "General Epistles",
  "3-john": "General Epistles",
  jude: "General Epistles",
  revelation: "Prophecy",
};
