/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownInputParams; } | { pathname: `/journal/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reader/[book]/[chapter]` | `/reader/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } } | { pathname: `/journal/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/journal/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownOutputParams; } | { pathname: `/journal/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reader/[book]/[chapter]` | `/reader/[book]/[chapter]`, params: Router.UnknownOutputParams & { book: string;chapter: string; } } | { pathname: `/journal/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/journal/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/journal${`?${string}` | `#${string}` | ''}` | `/journal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reader${`?${string}` | `#${string}` | ''}` | `/reader${`?${string}` | `#${string}` | ''}` | `/journal/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownInputParams; } | { pathname: `/journal/new`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/reader/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/reader/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/journal/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/journal/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/reader/[book]/[chapter]` | `/reader/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } } | { pathname: `/journal/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/journal/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
